### ISSUE TITLE
Add features to ScriptSelector

### ISSUE THREAD

**Issue by rabayliss** [mwgeurts/ray_scripts#11]
- [x] Link the script help documentation to a button created in a popup gui
- [x]  Create a popup that supplies the user with information on the progress of the script
- [x] Create an "abort" button which ends the script and returns the RS plan to the pre-script state

**Comment by mwgeurts** [comment]
- [ ] pull docstring, author tags for tooltip
- [ ] add form.dispose()

**Comment by mwgeurts** [comment]
- [ ] check RayStation version(s) against current version
