### ISSUE TITLE
Problem with Development General Script selector

### ISSUE THREAD

**Issue by rabayliss** [mwgeurts/ray_scripts#15]
![image](https://user-images.githubusercontent.com/37907358/38434771-30820616-3995-11e8-8016-0fb236e1838d.png)
Issue observed in launching of the "Development General" script from RS7
![capture](https://user-images.githubusercontent.com/37907358/38434825-6cdf46c8-3995-11e8-88bf-6822aa90900e.JPG)

**Comment by mwgeurts** [comment]
Which server is this on?

**Comment by rabayliss** [comment]
Have not been reassigned to onarray12.  Unsure if issue with requests is resolved

**Comment by mwgeurts** [comment]
I still haven't been able to get assigned to onarray12. I'm going to keep this open but punt it into the next sprint

**Comment by mwgeurts** [comment]
Issues confirmed, onarray12 will be re-imaged
