### ISSUE TITLE
Develop library functions for simple UI widgets

### ISSUE THREAD

**Issue by mwgeurts** [mwgeurts/ray_scripts#19]

**Comment by mwgeurts** [comment]
Started in a719f3ada01859134c651d5791dc95e4861ee84b

**Comment by rabayliss** [comment]
Dude, what’s up with the Hexy issue  name?  Want me to start tracking branches to issues this way?

**Comment by mwgeurts** [comment]
I'm just referencing a commit that relates to this issue (I forgot to in the original commit message)

**Comment by mwgeurts** [comment]
For marching table, apply a converging Levenshtein algorithm to supply the initial guess (if one isn’t provided)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mwgeurts** [comment]
Completed in a9b1043
