### ISSUE TITLE
Develop structure approval and TPO script

### ISSUE THREAD

**Issue by mwgeurts** [mwgeurts/ray_scripts#31]

**Comment by rabayliss** [comment]
- [ ] Add some optional prompts (Pacemaker, Chemo coordination, previous irradiation, reasons for IMRT versus 3D).  I'll reach out to Lori to get the comprehensive list of billable items.

**Comment by mwgeurts** [comment]
Beta version of the script is ready for evaluation. There isn't much use in developing this more until the doctors are involved.
