### ISSUE TITLE
Build DICOM export library function

### ISSUE THREAD

**Issue by mwgeurts** [mwgeurts/ray_scripts#39]
Below are some planned features:

- [x] prompt user to select a treatment room (which is mapped to a model)
- [x] update the machine name and energy/FFF tag, as needed
- [x] re-validate DICOM contents post adjustment to make sure other tags aren't affected
- [x] allow direct SCU/SCP export (validate against ARIA, MIM, Mobius3D)

**Comment by rabayliss** [comment]
- [ ] Find and kill the reference point definition in RT plan, replace with a single (fake) reference point which is defined by the prescription dose per fraction and number of fractions.
- [ ] Put in the following Couch values [ Vert: 0, Lng: 100, Lat:0]
- [ ] Set the block name dicom field from RS equal to the block ID (used by ARIA)

**Comment by mwgeurts** [comment]
- [ ] Allow optional (anonymized?) plan copy to get saved to a plan library, from #35

**Comment by rabayliss** [comment]
- [ ] Parse beamset name and technique: if 3D, 4th character of beamset is “R”, AND gantry angle 0 beam exists, prompt user to change to 180E

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mwgeurts** [comment]
What about using the isocenter position relative to CT center to determine whether or not to use 180E? If so, any idea on what threshold could be used?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mwgeurts** [comment]
v1 release branched to dicom_export for testing. I'll merge to master once others have had a chance to test it more broadly (and with a real beam model, not TB_Unified)
